name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: partA
      id: parta
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: partA
        setup-command: ''
        command: gradle test --tests "*partA*"
        timeout: 10
        max-score: 1
    - name: partB
      id: partb
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: partB
        setup-command: ''
        command: gradle test --tests "*partB*"
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PARTA_RESULTS: "${{steps.parta.outputs.result}}"
        PARTB_RESULTS: "${{steps.partb.outputs.result}}"
      with:
        runners: parta,partb
